# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [33]:
# Import pandas
import pandas as pd

In [34]:
# Create a series of three different colours
colours = pd.Series(["Red", "Grey", "Black"])

In [35]:
# View the series of different colours
colours

0      Red
1     Grey
2    Black
dtype: object

In [36]:
# Create a series of three different car types and view it
makes = pd.Series(["BMW", "Audi", "Vokswagen"])
makes

0          BMW
1         Audi
2    Vokswagen
dtype: object

In [38]:
# Combine the Series of cars and colours into a DataFrame
cars = pd.DataFrame({'Make': makes, 'Colour':colours})
cars

        Make Colour
0        BMW    Red
1       Audi   Grey
2  Vokswagen  Black

In [39]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [40]:
# Export the DataFrame you created to a .csv file
car_sales.to_csv("car_sales.csv")

In [ ]:
# Find the different datatypes of the car data DataFrame

In [ ]:
# Describe your current car sales DataFrame using describe()

In [ ]:
# Get information about your DataFrame using info()

What does it show you?

In [ ]:
# Create a Series of different numbers and find the mean of them

In [ ]:
# Create a Series of different numbers and find the sum of them

In [ ]:
# List out all the column names of the car sales DataFrame

In [ ]:
# Find the length of the car sales DataFrame

In [ ]:
# Show the first 5 rows of the car sales DataFrame

In [ ]:
# Show the first 7 rows of the car sales DataFrame

In [ ]:
# Show the bottom 5 rows of the car sales DataFrame

In [ ]:
# Use .loc to select the row at index 3 of the car sales DataFrame

In [ ]:
# Use .iloc to select the row at position 3 of the car sales DataFrame

Notice how they're the same? Why do you think this is?

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [ ]:
# Select the "Odometer (KM)" column from the car sales DataFrame

In [ ]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame

In [ ]:
# Select the rows with over 100,000 kilometers on the Odometer

In [ ]:
# Create a crosstab of the Make and Doors columns

In [ ]:
# Group columns of the car sales DataFrame by the Make column and find the average

In [ ]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline

In [ ]:
# Create a histogram of the Odometer column using hist()

In [ ]:
# Try to plot the Price column using plot()

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [ ]:
# Remove the punctuation from price column

In [ ]:
# Check the changes to the price column

In [ ]:
# Remove the two extra zeros at the end of the price column

In [ ]:
# Check the changes to the Price column

In [ ]:
# Change the datatype of the Price column to integers

In [ ]:
# Lower the strings of the Make column

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [ ]:
# Make lowering the case of the Make column permanent

In [ ]:
# Check the car sales DataFrame

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [ ]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")


# Check out the new DataFrame

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [ ]:
# Fill the Odometer column missing values with the mean of the column inplace

In [ ]:
# View the car sales missing DataFrame and verify the changes

In [ ]:
# Remove the rest of the missing data inplace

In [ ]:
# Verify the missing values are removed by viewing the DataFrame

We'll now start to add columns to our DataFrame.

In [ ]:
# Create a "Seats" column where every row has a value of 5

In [ ]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame

In [ ]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame

In [ ]:
# Remove the last column you added using .drop()

In [ ]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [ ]:
# Reset the indexes of the shuffled DataFrame

Notice the index numbers have been changed to have order (start from 0).

In [ ]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame

In [ ]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers

## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.